Sync formulas - makefile
salt-formulas/salt-formulas pull request #34
Opened 2017-05-25 07:53 UTC by epcim

use GH api to fetch list of salt-formulas

2017-05-25 08:28 UTC, fpytloun commented on Makefile
> +FORMULAS=`for i in 1 2 3 4 5; do curl -s "https://api.github.com/orgs/salt-formulas/repos?page=$$i&per_page=100" |grep -E 'clone_url.*salt-formula-' | sed 's/.*salt-formula-\([-_[:alnum:]]*\).git.*/\
`in 1 2 3 4 5` again..? :)
http://www.hovnokod.cz/3596

2017-05-25 08:35 UTC, fpytloun commented on Makefile
> +sync_submodules:
You have myrepos (.mrconfig) that should handle these things

2017-05-25 08:35 UTC, fpytloun commented on Makefile
> +sync_forks:
myrepos should handle this as well

2017-05-25 08:35 UTC, fpytloun requested changes
See comments

2017-05-26 16:36 UTC, epcim commented on Makefile
> +FORMULAS=`for i in 1 2 3 4 5; do curl -s "https://api.github.com/orgs/salt-formulas/repos?page=$$i&per_page=100" |grep -E 'clone_url.*salt-formula-' | sed 's/.*salt-formula-\([-_[:alnum:]]*\).git.*/\
not, its evaluated at the time the variable is used, welcome Makefile
let's keep that for the time we are over 500 formulas

2017-05-26 16:37 UTC, epcim commented on Makefile
> +sync_submodules:
is it adding submodule repos for new created repos? I think not.

2017-05-26 16:41 UTC, epcim commented on Makefile
> +sync_forks:
mi nefunguje `git-extras` na submodulech, tak si delam uplny clone do jineho adresare. Alternativa k myrepos.

tohle prida submodules a mrconfig je pak musi jeste najit a pridat do sveho coknfigu

2017-05-26 16:42 UTC, epcim commented on Makefile
> +FORMULAS=`for i in 1 2 3 4 5; do curl -s "https://api.github.com/orgs/salt-formulas/repos?page=$$i&per_page=100" |grep -E 'clone_url.*salt-formula-' | sed 's/.*salt-formula-\([-_[:alnum:]]*\).git.*/\
to pdf jsem urcite nechtel mazat..

2017-08-16 18:20 UTC, epcim commented
closed in favor of #48

2017-08-16 18:20 UTC, closed without merging