add bootstrap/validation/etc.. scripts [WIP]
salt-formulas/salt-formulas pull request #5
Opened 2017-02-03 13:18 UTC by epcim

need a location to store these files, we probably don't want individual repos, as well as we don't want to have multiple copies in each reclass-model/formula etc..

2017-02-05 14:03 UTC, kbaikov requested changes
Can you please use pep8 for py files and bashate or some other bash linter for sh files?

2017-02-05 14:03 UTC, kbaikov commented on scripts/check_jinja_recursive.py
> +  for root, dirnames, filenames in os.walk(path):
Can you please make it pep8 compatible.

2017-02-06 22:22 UTC, fpytloun commented on scripts/master_boostrap.sh
> +#!/bin/bash -e
This should probably go to `deploy/scripts` directory instead. And there's already some `setup-salt-master-pkg.sh`.

2017-02-06 22:26 UTC, fpytloun commented on scripts/master_init.sh
> +#!/usr/bin/env bash
I think this also belongs to `deploy/scripts` and should be also unified with what's in there now. There's suddenly a lot of shell scripts..

2017-02-06 22:27 UTC, fpytloun commented on scripts/salt_state_apply_trend.sh
> +# source: https://gist.github.com/epcim/e488af8be69b616eab3088a14a937e14
Description would be really helpful.

2017-02-07 08:01 UTC, merged